[versions]
kotlin = "1.6.10"
androidBuildTools = "7.1.0-rc01"

androidx-core = "1.7.0"
androidx-appcompat = "1.4.1"
material = "1.5.0"

[libraries]
kotlin-plugin-lib = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-plugin-lib = { module = "com.android.tools.build:gradle", version.ref = "androidBuildTools"}

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core"}
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat"}
material = { module = "com.google.android.material:material", version.ref = "material"}